// app/constants/icons.tsx
import {
  Menu,
  Bell,
  Search,
  User,
  X,
  Home,
  Users,
  FileText,
  Settings,
  LogOut,
  Eye,
  EyeOff,
  Mail,
  Lock,
  ArrowRight,
  Building,
  TrendingUp,
  Package,
  DollarSign,
  Calendar,
  ArrowUpRight,
  ArrowDownRight,
  Edit,
  Trash2,
  Plus,
  UserPlus,
  Inbox,
} from "lucide-react";

export const Icons = {
  menu: Menu,
  user: User,
  bell: Bell,
  search: Search,
  close: X,
  home: Home,
  users: Users,
  fileText: FileText,
  dollarSign: DollarSign,
  settings: Settings,
  logOut: LogOut,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  lock: Lock,
  arrowRight: ArrowRight,
  building: Building,
  trendingUp: TrendingUp,
  package: Package,
  calendar: Calendar,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  edit: Edit,
  trash2: Trash2,
  plus: Plus,
  userPlus: UserPlus,
  inbox: Inbox,
};
